functionsDirectory = "/Users/nihilnambiar/dream-dive/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []

[build]
publish = "/Users/nihilnambiar/dream-dive/build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]
directory = "netlify/functions"

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]